name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install dependencies
        run: |
          mamba install root

      - name: Print ROOT version
        run: |
          conda activate
          which root
          root-config --version
          root-config --cflags

      - uses: actions/checkout@v4

      - name: Build
        run: |
          # source root
          source /opt/conda/etc/profile.d/conda.sh
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
          cmake --build ${{github.workspace}}/build
